#
# Jekyll Configuraton for https://NocheProgramacion.com
#
#  ToDo for Jekyll v3.7:
#    - Agregar presentaciones Sozi
#

# --- Site Settings ---

# The site's title.
title:                        Noche Programacion // ALSW

# Location from where the site will be served (repository name for GitHub Pages).
baseurl:                      /

# Name of the GitHub repository (used for generating links to GitHub).
repository:                   alswnet/NocheProgramacion

# Prefix for download links (downloads only the relevant code from GitHub).
# TODO implementar DownGit de ALSW
github_download_prefix:       https://minhaskamal.github.io/DownGit/#/home?url=

# Prefixes for editor.p5js.org
web_editor_sketch_prefix:     https://editor.p5js.org/codingtrain/sketches/
web_editor_fullscreen_prefix: https://editor.p5js.org/full/

# Suffixes for auto-detecting the video's code that's available for download/preview.
#
# name          string  Name of the code variation.
# folder        string  Name of the folder relative to the video's repository.
# live_example  boolean Wether this variation should be used as the live example.
#                       The first match is used. If the video has the `web_editor`
#                       property, a link to the P5 Web Editor will be used instead.
code_variations:
  - name:                     "P5.JS"
    folder:                   "P5"
  - name:                     "Processing"
    folder:                   "Processing"
  - name:                     "JavaScript"
    folder:                   "JavaScript"
  - name:                     "Node.js"
    folder:                   "Node"
  - name:                     "Arduino"
    folder:                   "Arduino"
  - name:                     "Python"
    folder:                   "Python"
  - name:                     "Diagrama"
    folder:                   "Diagrama"
  - name:                     "HTML"
    folder:                   "HTML"

# Links to other platforms.
links:

  # link de ALSW.
  alsw:                       https://alsw.net

  # Tienda de ALSW
  tienda:                     https://alsw.net/tienda

  # Productos de alsw
  pieza:                      https://alsw.net/tienda/

  # Link to YouTube.
  youtube:                    https://youtube.com/alswnet

  # Link to Patreon.
  patreon:                    https://patreon.com/alswnet

  # Link de discord
  discord:                    https://discord.gg/ReRapub

  # Link de Donaciones
  paypal:                     https://www.paypal.me/alswnet

# --- Build Settings ---

# Use Kramdown as the preferred Markdown parser.
markdown:                     kramdown

# Exclude code for Node.js and Q_and_A
exclude:
  [
    "Node",
    "Q_and_A",
    "unit_testing",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]

# Include future videos (used for 'Upcoming Streams' section).
future:                       true

# Use El Salvador as the site's timezone.
timezone:                     America/El_Salvador

# Compress HTML for production builds.
compress_html: { ignore: { envs: ['development'] } }

# Search for SASS files inside assets/css.
sass: { sass_dir:             "assets/css" }

# Use jekyll-redirect-from to allow redirections
plugins:
  - jekyll-redirect-from

# --- Jekyll Locations ---
layouts_dir:                  _jekyll/layouts
includes_dir:                 _jekyll/includes

# --- Collections ---
collections:
  RetoProgramacion: { output: true }
  Cursos:           { output: true }
  Tutoriales:       { output: true }
  Guides:           { output: true }
  mas:              { output: true }

# --- Defaults ---

defaults:

  - scope:              { path: "", type: "RetoProgramacion" }
    values:
      layout:                 "video"
      video_type:             "reto programacion"
      video_type_short:       "reto"
      can_contribute:         false

  - scope:              { path: "", type: "Cursos" }
    values:
      layout:                 "video"
      video_type:             "curso"
      can_contribute:         false

  - scope:              { path: "", type: "Tutoriales" }
    values:
      layout:                 "video"
      video_type:             "tutoriales"
      video_type_short:       "tutorial"
      can_contribute:         false

  - scope: { path: "", type:  "Guides" }
    values:
      layout:                 "guide"

  - scope: { path: "", type:  "mas" }
    values:
      video_type:             "Video"
      layout:                 "video"
